run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/cliforge/cliforge
  revive:
    rules:
      - name: unused-parameter
        disabled: true  # Disable - parameters often required by interfaces/handlers

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
