package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

func newInitCmd() *cobra.Command {
	var (
		outputPath string
		cliName    string
		force      bool
	)

	cmd := &cobra.Command{
		Use:   "init [name]",
		Short: "Initialize a new CLI configuration",
		Long: `Initialize a new CLI configuration file (cli-config.yaml).

This command creates a starter configuration file with common settings
that you can customize for your API.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			// Determine CLI name
			if len(args) > 0 {
				cliName = args[0]
			}
			if cliName == "" {
				cliName = "my-cli"
			}

			// Determine output path
			if outputPath == "" {
				outputPath = "cli-config.yaml"
			}

			// Check if file exists
			if !force {
				if _, err := os.Stat(outputPath); err == nil {
					return fmt.Errorf("file %s already exists (use --force to overwrite)", outputPath)
				}
			}

			// Generate starter config
			config := generateStarterConfig(cliName)

			// Ensure directory exists
			dir := filepath.Dir(outputPath)
			if dir != "." {
				if err := os.MkdirAll(dir, 0755); err != nil {
					return fmt.Errorf("failed to create directory: %w", err)
				}
			}

			// Write config file
			if err := os.WriteFile(outputPath, []byte(config), 0644); err != nil {
				return fmt.Errorf("failed to write config file: %w", err)
			}

			fmt.Printf("✓ Created %s\n", outputPath)
			fmt.Printf("\nNext steps:\n")
			fmt.Printf("  1. Edit %s to configure your CLI\n", outputPath)
			fmt.Printf("  2. Run 'cliforge validate' to check your configuration\n")
			fmt.Printf("  3. Run 'cliforge build' to generate your CLI binary\n")

			return nil
		},
	}

	cmd.Flags().StringVarP(&outputPath, "output", "o", "", "Output path for config file (default: cli-config.yaml)")
	cmd.Flags().StringVarP(&cliName, "name", "n", "", "CLI name (default: my-cli)")
	cmd.Flags().BoolVarP(&force, "force", "f", false, "Overwrite existing file")

	return cmd
}

func generateStarterConfig(cliName string) string {
	return fmt.Sprintf(`metadata:
  name: %s
  version: 1.0.0
  description: A CLI tool generated by CliForge
  author:
    name: Your Name
    email: you@example.com

branding:
  colors:
    primary: "#0066CC"
    secondary: "#FF6600"
    success: "#00CC66"
    warning: "#FFCC00"
    error: "#CC0000"

api:
  openapi_url: ./openapi.yaml
  base_url: https://api.example.com
  timeout: 30s

defaults:
  output:
    format: json
    pretty_print: true
    color: auto
  http:
    timeout: 30s
  caching:
    enabled: true
  retry:
    max_attempts: 3

behaviors:
  auth:
    type: api_key
    api_key:
      header: X-API-Key
      env_var: %s_API_KEY

  caching:
    spec_ttl: 5m
    response_ttl: 1m

  builtin_commands:
    version:
      enabled: true
    help:
      enabled: true
    completion:
      enabled: true
      shells: [bash, zsh, fish, powershell]

  global_flags:
    output:
      enabled: true
      flag: "--output"
      short: "-o"
      description: "Output format (json|yaml|table)"
    verbose:
      enabled: true
      flag: "--verbose"
      short: "-v"
      description: "Enable verbose output"

updates:
  enabled: false
  # update_url: https://releases.example.com/my-cli
  # check_interval: 24h

features:
  config_file: true
  interactive_mode: false
`, cliName, toEnvVarPrefix(cliName))
}

func toEnvVarPrefix(name string) string {
	// Convert CLI name to environment variable prefix
	// e.g., "my-cli" -> "MY_CLI"
	result := ""
	for _, c := range name {
		if c >= 'a' && c <= 'z' {
			result += string(c - 'a' + 'A')
		} else if c >= 'A' && c <= 'Z' {
			result += string(c)
		} else if c >= '0' && c <= '9' {
			result += string(c)
		} else {
			result += "_"
		}
	}
	return result
}
